/**
 * Module: githubPagesPublisher
 * Purpose: Publish Markdown generated by local Ollama directly to a GitHub Pages repository via Content API.
 */

import { generateBlogWithOllama } from "./ollamaClient.js";

// Placeholder configuration values (replace with your own secrets and repo identifiers).
export const GITHUB_PAT = "YOUR_GITHUB_PAT_HERE";
export const GITHUB_REPO_OWNER = "YOUR_GITHUB_USERNAME_OR_ORG";
export const GITHUB_REPO_NAME = "YOUR_GITHUB_PAGES_REPOSITORY";
export const GITHUB_DEFAULT_BRANCH = "main";

function base64EncodeUtf8(value) {
  const bytes = new TextEncoder().encode(value);
  let binary = "";
  for (const b of bytes) {
    binary += String.fromCharCode(b);
  }
  return btoa(binary);
}

/**
 * Pushes markdown content to GitHub using:
 * PUT https://api.github.com/repos/{owner}/{repo}/contents/{path}
 *
 * @param {Object} params
 * @param {string} params.path - Repository-relative file path (example: posts/my-post.md).
 * @param {string} params.markdown - Markdown content to publish.
 * @param {string|null} [params.sha=null] - Existing blob SHA for updates.
 * @returns {Promise<Object>} GitHub API response payload.
 */
export async function pushMarkdownToGitHubPages({ path, markdown, sha = null }) {
  if (!path || !path.trim()) {
    throw new Error("GitHub path is required (for example: posts/my-post.md).");
  }
  if (!markdown || !markdown.trim()) {
    throw new Error("Markdown content is empty.");
  }
  if (!GITHUB_PAT || GITHUB_PAT.includes("YOUR_GITHUB_PAT")) {
    throw new Error("Set GITHUB_PAT in src/githubPagesPublisher.js before publishing.");
  }

  const apiUrl = `https://api.github.com/repos/${GITHUB_REPO_OWNER}/${GITHUB_REPO_NAME}/contents/${encodeURI(
    path.replace(/^\/+/, "")
  )}`;

  const payload = {
    message: `chore(content): publish ${path}`,
    content: base64EncodeUtf8(markdown),
    branch: GITHUB_DEFAULT_BRANCH,
  };

  if (sha) {
    payload.sha = sha;
  }

  const response = await fetch(apiUrl, {
    method: "PUT",
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${GITHUB_PAT}`,
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
    },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`GitHub Content API publish failed: ${response.status} ${errorText}`);
  }

  return response.json();
}

/**
 * Voice-first workflow helper:
 * 1) Ask local Ollama for Markdown.
 * 2) Push Markdown directly to GitHub Pages repo.
 *
 * @param {Object} params
 * @param {string} params.transcript - Voice transcript text.
 * @param {string} params.systemPrompt - Prompt describing blog output behavior.
 * @param {string} params.path - GitHub destination path (example: posts/2026-03-13.md).
 * @param {string|null} [params.sha=null] - Existing blob SHA for updates.
 * @returns {Promise<{markdown: string, publish: Object}>}
 */
export async function voicePublishToGitHub({ transcript, systemPrompt, path, sha = null }) {
  const markdown = await generateBlogWithOllama({
    transcript,
    systemPrompt,
    outputFormat: "markdown",
  });

  const publish = await pushMarkdownToGitHubPages({
    path,
    markdown,
    sha,
  });

  return { markdown, publish };
}
